/* this script should start stockManager.script for EVERY SYMBOL with a given PER STOCK budget *
 * the arg passed to this script should be the TOTAL budget needed, and we'll calculate per stock here */


var symbols = stock.getSymbols();
var perStockBudget = args[0]/symbols.length;


for (var i = 0; i < symbols.length; i++){
	run ("stockManager.script", 1, symbols[i], perStockBudget);
}