/* to be ran at the start of an augmentation */
var servers = scan("home");

for (var i = 0; i < servers.length; i++) {
	run("quickRootAttempt.script", 1, servers[i]);
}

run("quickRootAttempt.script", 1, "zer0");
run("quickRootAttempt.script", 1, "neo-net");
run("quickRootAttempt.script", 1, "nectar-net");
run("quickRootAttempt.script", 1, "max-hardware");

//run("serverPurchaser.script", 1, "16");
run("massHackAllRoots.script", 1);